FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py pdf_utils.py ./

EXPOSE 8082
CMD ["gunicorn","-b","0.0.0.0:8082","-w","2","app:app"]

